version: '3.7'

services:
    xiubox-client:
        image: xiubox
        container_name: xiubox-client
        build:
            context: ..
            dockerfile: dockerfile.prod
        ports:
            - 80:80
        stdin_open: true
        restart: on-failure
