name: Client
on:
    push:
        branches:
            - main
        paths:
            - src/**
jobs:
    build:
        name: Deploy
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Build prod
              run: docker-compose -f dev/docker-compose.prod.yml build
            - name: Run prod
              run: docker-compose -f dev/docker-compose.prod.yml up -d
            - name: Prune old image caches
              run: docker image prune -f
